In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/shyennecarter/movie-data-base/archive/mymoviedb (1).csv

In [4]:
import pandas as pd
df=pd.read_csv("/kaggle/input/datasets/shyennecarter/movie-data-base/archive/mymoviedb (1).csv",
              engine = "python",
              on_bad_lines="skip"
)
df.head()

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
0,2021-12-15,Spider-Man: No Way Home,Peter Parker is unmasked and no longer able to...,5083.954,8940,8.3,en,"Action, Adventure, Science Fiction",https://image.tmdb.org/t/p/original/1g0dhYtq4i...
1,2022-03-01,The Batman,"In his second year of fighting crime, Batman u...",3827.658,1151,8.1,en,"Crime, Mystery, Thriller",https://image.tmdb.org/t/p/original/74xTEgt7R3...
2,2022-02-25,No Exit,Stranded at a rest stop in the mountains durin...,2618.087,122,6.3,en,Thriller,https://image.tmdb.org/t/p/original/vDHsLnOWKl...
3,2021-11-24,Encanto,"The tale of an extraordinary family, the Madri...",2402.201,5076,7.7,en,"Animation, Comedy, Family, Fantasy",https://image.tmdb.org/t/p/original/4j0PNHkMr5...
4,2021-12-22,The King's Man,As a collection of history's worst tyrants and...,1895.511,1793,7.0,en,"Action, Adventure, Thriller, War",https://image.tmdb.org/t/p/original/aq4Pwv5Xeu...

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.8+ KB

In [6]:
df.describe(include='all')

,Release_Date,Title,Overview,Popularity,Vote_Count,Vote_Average,Original_Language,Genre,Poster_Url
count,9837,9828,9828,9827.000000,9827,9827,9827,9826,9826
unique,5903,9514,9823,NaN,3267,75,44,2337,9826
top,2022-03-10,Beauty and the Beast,Dr. Raichi is one of the only survivors of the...,NaN,0,6.4,en,Drama,https://image.tmdb.org/t/p/original/1g0dhYtq4i...
freq,16,4,2,NaN,100,435,7569,466,1
mean,NaN,NaN,NaN,40.320570,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,108.874308,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,7.100000,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,16.127500,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,21.191000,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,35.174500,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,5083.954000,NaN,NaN,NaN,NaN,NaN

In [7]:
df.isnull().sum

<bound method DataFrame.sum of       Release_Date  Title  Overview  Popularity  Vote_Count  Vote_Average  \
0            False  False     False       False       False         False
1            False  False     False       False       False         False
2            False  False     False       False       False         False
3            False  False     False       False       False         False
4            False  False     False       False       False         False
...            ...    ...       ...         ...         ...           ...
9832         False  False     False       False       False         False
9833         False  False     False       False       False         False
9834         False  False     False       False       False         False
9835         False  False     False       False       False         False
9836         False  False     False       False       False         False

      Original_Language  Genre  Poster_Url
0                 False  False       False
1                 False  False       False
2                 False  False       False
3                 False  False       False
4                 False  False       False
...                 ...    ...         ...
9832              False  False       False
9833              False  False       False
9834              False  False       False
9835              False  False       False
9836              False  False       False

[9837 rows x 9 columns]>

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.isnull().sum()

Release_Date          0
Title                 9
Overview              9
Popularity           10
Vote_Count           10
Vote_Average         10
Original_Language    10
Genre                11
Poster_Url           11
dtype: int64

In [10]:
df.columns

Index(['Release_Date', 'Title', 'Overview', 'Popularity', 'Vote_Count',
       'Vote_Average', 'Original_Language', 'Genre', 'Poster_Url'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9837 non-null   object
 1   Title              9828 non-null   object
 2   Overview           9828 non-null   object
 3   Popularity         9827 non-null   float64
 4   Vote_Count         9827 non-null   object
 5   Vote_Average       9827 non-null   object
 6   Original_Language  9827 non-null   object
 7   Genre              9826 non-null   object
 8   Poster_Url         9826 non-null   object
dtypes: float64(1), object(8)
memory usage: 691.8+ KB

In [24]:
# Convert Release_Date to datetime
df["Release_Date"] = pd.to_datetime(df["Release_Date"], errors="coerce")

# Convert Vote_Count and Vote_Average to numeric
df["Vote_Count"] = pd.to_numeric(df["Vote_Count"], errors="coerce")
df["Vote_Average"] = pd.to_numeric(df["Vote_Average"], errors="coerce")
df["Title"] = df["Title"].fillna("Unknown")
df["Overview"] = df["Overview"].fillna("Unknown")
df["Original_Language"] = df["Original_Language"].fillna("Unknown")
df["Genre"] = df["Genre"].fillna("Unknown")
df["Poster_Url"] = df["Poster_Url"].fillna("Unknown")

df["Popularity"] = df["Popularity"].fillna(0)
df["Vote_Count"] = df["Vote_Count"].fillna(0)
df["Vote_Average"] = df["Vote_Average"].fillna(0)

df["Title"] = df["Title"].str.strip().str.title()
df["Overview"] = df["Overview"].str.strip()
df["Original_Language"] = df["Original_Language"].str.strip().str.lower()
df["Genre"] = df["Genre"].str.strip().str.title()

df = df[(df["Vote_Average"] >= 0) & (df["Vote_Average"] <= 10)]
df = df[df["Vote_Count"] >= 0]
df = df[df["Popularity"] >= 0]

df.info()
df.isnull().sum()
df.duplicated().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   datetime64[ns]
 1   Title              9837 non-null   object
 2   Overview           9837 non-null   object
 3   Popularity         9837 non-null   float64
 4   Vote_Count         9837 non-null   float64
 5   Vote_Average       9837 non-null   float64
 6   Original_Language  9837 non-null   object
 7   Genre              9837 non-null   object
 8   Poster_Url         9837 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 691.8+ KB

np.int64(8)

In [26]:
df.to_csv("cleaned_movies.csv", index=False)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9837 entries, 0 to 9836
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Release_Date       9827 non-null   datetime64[ns]
 1   Title              9837 non-null   object
 2   Overview           9837 non-null   object
 3   Popularity         9837 non-null   float64
 4   Vote_Count         9837 non-null   float64
 5   Vote_Average       9837 non-null   float64
 6   Original_Language  9837 non-null   object
 7   Genre              9837 non-null   object
 8   Poster_Url         9837 non-null   object
dtypes: datetime64[ns](1), float64(3), object(5)
memory usage: 691.8+ KB

In [30]:
df.to_csv("/kaggle/working/cleaned_movies.csv", index=False)